FROM alpine:latest

RUN apk add --update avahi && \
    sed -i 's/#enable-reflector=no/enable-reflector=yes/g' /etc/avahi/avahi-daemon.conf && \
    rm -rf /var/cache/apk/*

VOLUME /etc/avahi/services
EXPOSE 5353/udp

ENTRYPOINT ["avahi-daemon"]
CMD []