# FROM --platform=linux/amd64 aclemons/slackware:15.0
FROM aclemons/slackware:15.0

RUN mkdir -p /var/lock/

COPY ./ /root/
WORKDIR /root/

RUN ["docker/slackware_init.sh"]
CMD ["install.sh"]
ENTRYPOINT ["/bin/bash"]